---
# tasks file for install the module

- debug:
    msg: ">>{{ item.strip() }}<<"
  with_items: "{{ pre_install.split(';') }}"
  when: pre_install not in ''   
   
- name: "Execute pre-install commands"
  shell: "{{ item.strip() }}"
  with_items: "{{ pre_install.split(';') }}"
  when: pre_install not in ''
  
- name: "Remove symlink"
  file:
    path: "{{dist_remotedir_run}}/{{dist_appname}}"
    state: absent

- name: "TAR: create symbolic link"
  file:
    src: "{{dist_remotedir_install}}/{{dist_appname}}-1.0-{{TAG_NAME}}"
    dest: "{{dist_remotedir_run}}/{{dist_appname}}"
    owner: root
    group: root
    state: link
  when: EXT == "tar"

- name: "WAR: create symbolic link"
  file:
    src: "{{dist_remotedir_install}}/{{dist_appname}}-1.0-{{TAG_NAME}}.{{EXT}}"
    dest: "{{dist_remotedir_run}}/{{dist_appname}}.{{EXT}}"
    owner: root
    group: root
    state: link
  when: EXT == "war"

- name: "Execute post-install commands"
  shell: "{{ item.strip() }}"
  with_items: "{{ post_install.split(';') }}"
  when: post_install not in ''
