---

# file: code-checkout.yml
# This playbook checkout required code repositories onto remote server.

- hosts: torni
  connection: local

  vars:
   - GITHUB_REPO_URL: git@github.devcloud.elisa.fi:jpd/devel.git
   
  tasks:
   
  - name: "Create required folder structure"
    file:
     state: directory
     path: "{{item}}"
    with_items:
     - "{{ ansible_env.HOME }}/workspace/auto-deploy-workspace/{{MODULE_NAME}}"
     
  - name: "Checkout repository from TAG"
    git: 
     repo: "{{GITHUB_REPO_URL}}"
     dest: "{{ ansible_env.HOME }}/workspace/auto-deploy-workspace/{{MODULE_NAME}}"
     version: "{{TAG_NAME}}"
     accept_hostkey: True
     force: yes     

#  roles:
#   - code-checkout
