# file: generic_commands.yml
# This playbook execute the command on the prod server.

- hosts: bog
  connection: local
  serial: 1
  
  vars:
    - contents: "{{ lookup('file','/var/lib/jenkins/workspace/GDPR/ready-for-testing-migration/Generic_Commands/Ag4-smsorder_(Commands)/vars/genericCommands/ag4-smsorder/genericCommands.yml')}}"
    - param: "{{ PARAMETER | regex_replace('%20',' ') }}"
    
  tasks:
  - debug:
      var: param
      
  - debug:
      var: contents
      
  - fail: 
      msg: "command not in git file"
    when: param not in contents
