---

# file: execute-on-remote.yml
# This playbook execute the command on the remote server.

- hosts: "{{REMOTE_HOSTS_GROUP}}"
  connection: local
  serial: 1
  
  vars_files:
   - vars/prod/prepaid/static-promutuus-web1.yml
   
  vars:
   - svn_files: "{{ dist_app_env_svn_files | default('')}}"
   
   
  tasks:
  
   - name: show if defined
     debug:
       msg: "variable is defined :=> {{ svn_files }}"
     with_items: "{{ svn_files.split(';') }}"
     when: EXT == "war" and svn_files not in ''
       
       
#    with_items: "{{ dist_app_env_svn_files.split(';') }}"
#    when: EXT =="war" and dist_app_env_svn_files is defined
     

  
#  - name: "test"
#    debug:
#      msg: "{{ item }}"
#    with_items: "{{ dist_app_env_svn_files.split(';') |default('') }}"
#    when: EXT == "tar" and read_env_svn_files == "true"
  
#  - name: "replace the svn file for tar in etc"
#    copy:
#      src: "{{ansible_env.HOME}}/ansible/svn/{{ item }}"
#      dest: "{{ansible_env.HOME}}/ansible/deploy/{{dist_appname}}-1.0-{{TAG_NAME}}/etc/"
#    with_items: "{{ dist_app_env_svn_files.split(';') | default([]) }}"
#    when: EXT == "tar" and read_env_svn_files == "true"
