---

# file: node_enable.yml
# This playbook enables cluster node on the production server

- hosts: "{{REMOTE_HOSTS_GROUP}}"
  remote_user: root
  serial: 1

  tasks:
  - name: Enable 
    shell: "iptables -F INPUT"
